/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthTestRouteImport } from './routes/auth-test'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotiRouteImport } from './routes/_app.noti'
import { Route as AppBrowseRouteImport } from './routes/_app.browse'
import { Route as AppAddRouteImport } from './routes/_app.add'
import { Route as AppProjectChatRouteImport } from './routes/_app.project.chat'

const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth-test',
  path: '/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotiRoute = AppNotiRouteImport.update({
  id: '/noti',
  path: '/noti',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectChatRoute = AppProjectChatRouteImport.update({
  id: '/project/chat',
  path: '/project/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-test': typeof AuthTestRoute
  '/add': typeof AppAddRoute
  '/browse': typeof AppBrowseRoute
  '/noti': typeof AppNotiRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/project/chat': typeof AppProjectChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-test': typeof AuthTestRoute
  '/add': typeof AppAddRoute
  '/browse': typeof AppBrowseRoute
  '/noti': typeof AppNotiRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/project/chat': typeof AppProjectChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth-test': typeof AuthTestRoute
  '/_app/add': typeof AppAddRoute
  '/_app/browse': typeof AppBrowseRoute
  '/_app/noti': typeof AppNotiRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/project/chat': typeof AppProjectChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-test'
    | '/add'
    | '/browse'
    | '/noti'
    | '/profile'
    | '/projects'
    | '/project/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-test'
    | '/add'
    | '/browse'
    | '/noti'
    | '/profile'
    | '/projects'
    | '/project/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth-test'
    | '/_app/add'
    | '/_app/browse'
    | '/_app/noti'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/project/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthTestRoute: typeof AuthTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth-test': {
      id: '/auth-test'
      path: '/auth-test'
      fullPath: '/auth-test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/noti': {
      id: '/_app/noti'
      path: '/noti'
      fullPath: '/noti'
      preLoaderRoute: typeof AppNotiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse': {
      id: '/_app/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add': {
      id: '/_app/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/chat': {
      id: '/_app/project/chat'
      path: '/project/chat'
      fullPath: '/project/chat'
      preLoaderRoute: typeof AppProjectChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppBrowseRoute: typeof AppBrowseRoute
  AppNotiRoute: typeof AppNotiRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppProjectChatRoute: typeof AppProjectChatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppBrowseRoute: AppBrowseRoute,
  AppNotiRoute: AppNotiRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppProjectChatRoute: AppProjectChatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthTestRoute: AuthTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
