/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthTestRouteImport } from './routes/auth-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsBrowseRouteImport } from './routes/projects/browse'

const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth-test',
  path: '/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBrowseRoute = ProjectsBrowseRouteImport.update({
  id: '/projects/browse',
  path: '/projects/browse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-test': typeof AuthTestRoute
  '/projects/browse': typeof ProjectsBrowseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-test': typeof AuthTestRoute
  '/projects/browse': typeof ProjectsBrowseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-test': typeof AuthTestRoute
  '/projects/browse': typeof ProjectsBrowseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth-test' | '/projects/browse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth-test' | '/projects/browse'
  id: '__root__' | '/' | '/auth-test' | '/projects/browse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthTestRoute: typeof AuthTestRoute
  ProjectsBrowseRoute: typeof ProjectsBrowseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth-test': {
      id: '/auth-test'
      path: '/auth-test'
      fullPath: '/auth-test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/browse': {
      id: '/projects/browse'
      path: '/projects/browse'
      fullPath: '/projects/browse'
      preLoaderRoute: typeof ProjectsBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthTestRoute: AuthTestRoute,
  ProjectsBrowseRoute: ProjectsBrowseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
